### ISSUE TITLE
broken image URL in help documentation

### ISSUE THREAD

**Issue by jtkulas** [surveydown-dev/demos#1]
Thanks for the package - been having a lot of fun looking into it!!

I found a couple of old URL links that appear broken on your "[Question Formatting](https://surveydown.org/question-formatting#html-formatting)" help page (html section).

The links appear to direct to an older folder configuration: https://github.com/surveydown-dev/demos/blob/main/choice-based-conjoint/images/fuji.jpg

obviously not a huge deal, but I figured I'd drop a friendly note!! Thanks

**Comment by jhelvy** [comment]
Thanks! That was fast - we literally just created the demos repo today (previously each demo was in a separate repo). Still fixing all the links on the main site, but these ones slipped through!

**Comment by jhelvy** [comment]
Okay links are now fixed!
